ALTER TABLE user_activities 
ADD COLUMN IF NOT EXISTS country VARCHAR(50) DEFAULT 'Unknown',
ADD COLUMN IF NOT EXISTS region VARCHAR(50) DEFAULT 'Unknown',
ADD COLUMN IF NOT EXISTS city VARCHAR(50) DEFAULT 'Unknown',
ADD COLUMN IF NOT EXISTS timezone VARCHAR(50) DEFAULT 'Unknown',
ADD COLUMN IF NOT EXISTS language VARCHAR(20) DEFAULT 'Unknown';
